version: '3.9'

services:
  mysql:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    env_file: ./infra/mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '53306:3306'
    volumes:
      - ./infra/mysql/conf:/etc/mysql/conf.d/
      - mysqldata:/var/lib/mysql
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    env_file: ./infra/app/app.env
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '53000:3000'
    volumes:
      - ./src:/app
    working_dir: /app
    command: yarn start
    networks:
      - default
    depends_on:
      - mysql
networks:
  default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata: