version: '3'
services:
 mysql:
   image: mysql:8.0
   env_file: ./mysql/mysql.env
   environment:
     - TZ=Asia/Tokyo
   ports:
     - '53306:3306'
   volumes:
     - ./mysql/conf:/etc/mysql/conf.d/:ro
     - mysqldata:/var/lib/mysql
   networks:
     - default
 app:
   image: node:16
  #  env_file: ./app.env
   environment:
     - DEBUG=app:*
   tty: true
   ports:
     - '53000:3000'
   volumes:
     - ./src:/app
   working_dir: /app
   command: yarn dev
   networks:
     - default
   depends_on:
     - mysql
networks:
 default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
 mysqldata: